name: Deploy API Response

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
permissions:
  contents: read
  pages: write
  id-token: write

steps:
  - name: Download API Response
    run: |
      Y=$(date -d "yesterday" +%Y)
      M=$(date -d "yesterday" +%m)
      D=$(date -d "yesterday" +%Y-%m-%d)

      URL="http://122.155.135.51/api/map/climateContourGeo?t=period&y=$Y&m=$M&fd=$D&td=$D&f=rf_sum"

      curl -L "$URL" -o index.html

  - name: Setup Pages
    uses: actions/configure-pages@v4

  - name: Upload Artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: .

  - name: Deploy to GitHub Pages
    uses: actions/deploy-pages@v4
```
